#
#  Ubuntu OS
#

# Base image

FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu22.04 AS base

# Make home default directory

WORKDIR /root

# Environment variables

ENV TERM="xterm-256color"

ARG TARGETOS
ARG TARGETARCH

# Update package registry

RUN apt update && apt upgrade --yes

# Remove old packages

RUN apt remove --yes --allow-change-held-packages \
    ibverbs-utils \
    libibverbs-dev \
    libibverbs1 \
    libmlx5-1 \
    libnccl2 \
    libnccl-dev

RUN rm -rf /opt/hpcx \
    && rm -rf /usr/local/mpi \
    && rm -f /etc/ld.so.conf.d/hpcx.conf \
    && ldconfig

# Update timezone

RUN DEBIAN_FRONTEND=noninteractive TZ=America/New_York \
    apt install -y tzdata && \
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    echo "America/New_York" > /etc/timezone && \
    dpkg-reconfigure --frontend noninteractive tzdata

# Install software

RUN apt install --yes \
    bash-completion \
    build-essential \
    curl \
    expect \
    git \
    gpg \
    gnupg \
    iputils-ping \
    lsb-release \
    openssh-client \
    openssh-server \
    screen \
    software-properties-common \
    sudo \
    tree \
    unzip \
    vim \
    wget

# Install Python

RUN add-apt-repository ppa:deadsnakes/ppa --yes && \
    apt update && \
    apt install --yes python3.12 python3.12-venv python3.12-dev && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12 && \
    ln -s /usr/bin/python3.12 /usr/local/bin/python && \
    ln -s /usr/bin/python3.12 /usr/local/bin/python3

# Install uv

RUN curl -LsSf https://astral.sh/uv/install.sh | \
    env UV_INSTALL_DIR=/usr/local/bin INSTALLER_NO_MODIFY_PATH=1 sh

# Install AWS CLI

RUN if [ "${TARGETARCH}" = "arm64" ]; then AWS_ARCH="aarch64"; else AWS_ARCH="x86_64"; fi && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-${AWS_ARCH}.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip

# Install Kubectl

RUN curl -fL -o /usr/local/bin/kubectl "https://dl.k8s.io/release/$(curl -fsSL https://dl.k8s.io/release/stable.txt)/bin/${TARGETOS}/${TARGETARCH}/kubectl" && \
    chmod 0755 /usr/local/bin/kubectl

# Install Claude Code

RUN curl -fsSL https://claude.ai/install.sh | bash && \
    cp -L /root/.local/bin/claude /usr/local/bin/claude && \
    chmod 0755 /usr/local/bin/claude

# Install Terraform

RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list && \
    apt update && apt install terraform

# Install Helm

RUN curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | tee /etc/apt/sources.list.d/helm-stable-debian.list && \
    apt update && apt install helm

# Install Docker CLI

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=${TARGETARCH} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt update && apt install --yes docker-ce-cli

# Install nerdctl

RUN NERDCTL_VERSION=$(curl -s https://api.github.com/repos/containerd/nerdctl/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//') && \
    wget https://github.com/containerd/nerdctl/releases/download/v${NERDCTL_VERSION}/nerdctl-full-${NERDCTL_VERSION}-linux-${TARGETARCH}.tar.gz && \
    tar -xzvf nerdctl-full-${NERDCTL_VERSION}-linux-${TARGETARCH}.tar.gz -C /usr/local && \
    rm nerdctl-full-${NERDCTL_VERSION}-linux-${TARGETARCH}.tar.gz

# Install just

RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

# Download GNU screen utilities

RUN git clone https://github.com/metalcycling/screen-utils.git /opt/screen/utils
ENV PATH="/opt/screen/utils:${PATH}"

# Copy environment files

RUN git clone https://github.com/metalcycling/mubuntu.git /opt/mubuntu
RUN cp -rT /opt/mubuntu/Files /root
RUN rm -rf /opt/mubuntu
RUN tar -xvf ~/.vim/pack.tar -C ~/.vim
RUN rm ~/.vim/pack.tar

# Clean registry

RUN apt clean && \
    rm -rf /var/lib/apt/lists/*

# Command to run

CMD ["/bin/bash"]
